"""Econometric and quantitative analytical modeling subpackage.

Purpose: Contains advanced quantitative transformations, labeling algorithms, and statistical tests.
Dependencies: numpy, scipy, statsmodels, pyarrow, domain models.
Relationship: Consumed by application services and research pipelines.
"""

from quant.analytics.chromosomes import (
    GENE_REGISTRY,
    ChromosomeVectorCodec,
    GameTheoryChromosome,
    GeneSpec,
    InferenceChromosome,
    RepresentationChromosome,
    RiskChromosome,
    ScaleType,
    StrategyChromosome,
)
from quant.analytics.cross_validation import (
    CombinatorialPurgedCV,
    CPCVConfig,
    PurgedSplit,
)
from quant.analytics.deflated_sharpe import (
    DeflatedSharpeEngine,
    DSRConfig,
    DSRResult,
    adjust_p_values_fdr,
    compute_effective_trials,
    compute_expected_max_sharpe,
    compute_min_backtest_length,
    compute_moments,
    compute_probabilistic_sharpe_ratio,
)
from quant.analytics.evolutionary_lifecycle import (
    AdaptiveVolatilityMutator,
    GenerationalLifecycleEngine,
    GenerationalState,
    InvalidGenerationalStateException,
    LifecycleError,
    LifecycleStepResult,
    MutationConfig,
    StagnationDetector,
    StagnationException,
    StagnationReport,
)
from quant.analytics.fractional_diff import (
    FractionalDifferentiator,
    StreamingFracDiffBuffer,
    compute_fractional_weights,
)
from quant.analytics.hypergamic_selection import (
    AsymmetricLatentCrossover,
    HypergamicConfig,
    HypergamicPartnerMatcher,
    HypergamicSelectionEngine,
    HypergamicSelectionError,
    InvalidCohortException,
    MatingDeadlockException,
    MatingPair,
    OffspringResult,
    ParetoCohortStratifier,
    ResidualOrthogonalityGate,
)
from quant.analytics.labeling import (
    BarrierLabel,
    BarrierTouchReason,
    DynamicTripleBarrierLabeler,
    PositionSide,
    TripleBarrierConfig,
    compute_parkinson_volatility,
)
from quant.analytics.market_impact import (
    DepletionState,
    GeneralizedPseudoHuber,
    HubermanStanzlCrossImpact,
    MarketImpactConfig,
    MarketImpactResult,
    MultiAssetMarketImpactEngine,
)
from quant.analytics.meta_labeling import (
    ContinuousKellySizer,
    MetaLabel,
    MetaLabelConfig,
    ProbabilityCalibrator,
    TwoStageMetaLabeler,
)
from quant.analytics.minimax_regret import (
    EntropicBoltzmannPotential,
    LatentSoftmaxTransform,
    MinimaxRegretConfig,
    OptimizationResult,
    VectorizedNewtonSolver,
)
from quant.analytics.pareto_sorting import (
    AdaptiveReferenceLattice,
    BoundaryAnchoredRVEARanker,
    CandidateFitness,
    CorruptedFitnessException,
    DegenerateLatticeException,
    DependentNonDominatedSorter,
    InvalidResidualException,
    ParetoFront,
    ParetoSortingError,
    RankingResult,
    SVDSubspaceOrthogonalArchive,
)
from quant.analytics.payoff_matrix import (
    BenchmarkEvaluationResult,
    DiscreteHyperbolicPropagator,
    InstitutionalBenchmarkUniverse,
    PayoffTensorResult,
    StackelbergConfig,
    StackelbergPayoffEngine,
    StackelbergPayoffTensorConstructor,
)
from quant.analytics.regimes import (
    CausalBayesianRegimeFilter,
    CUSUMJumpDetector,
    OASCovarianceEstimator,
    RegimeConfig,
    RegimeEstimationResult,
    RegimeState,
)

__all__ = [
    "AdaptiveReferenceLattice",
    "AdaptiveVolatilityMutator",
    "AsymmetricLatentCrossover",
    "BarrierLabel",
    "BarrierTouchReason",
    "BenchmarkEvaluationResult",
    "BoundaryAnchoredRVEARanker",
    "CPCVConfig",
    "CUSUMJumpDetector",
    "CandidateFitness",
    "CausalBayesianRegimeFilter",
    "ChromosomeVectorCodec",
    "CombinatorialPurgedCV",
    "ContinuousKellySizer",
    "CorruptedFitnessException",
    "DSRConfig",
    "DSRResult",
    "DeflatedSharpeEngine",
    "DegenerateLatticeException",
    "DependentNonDominatedSorter",
    "DepletionState",
    "DiscreteHyperbolicPropagator",
    "DynamicTripleBarrierLabeler",
    "EntropicBoltzmannPotential",
    "FractionalDifferentiator",
    "GENE_REGISTRY",
    "GameTheoryChromosome",
    "GeneSpec",
    "GeneralizedPseudoHuber",
    "GenerationalLifecycleEngine",
    "GenerationalState",
    "HubermanStanzlCrossImpact",
    "HypergamicConfig",
    "HypergamicPartnerMatcher",
    "HypergamicSelectionEngine",
    "HypergamicSelectionError",
    "InferenceChromosome",
    "InstitutionalBenchmarkUniverse",
    "InvalidCohortException",
    "InvalidGenerationalStateException",
    "InvalidResidualException",
    "LatentSoftmaxTransform",
    "LifecycleError",
    "LifecycleStepResult",
    "MarketImpactConfig",
    "MarketImpactResult",
    "MatingDeadlockException",
    "MatingPair",
    "MetaLabel",
    "MetaLabelConfig",
    "MinimaxRegretConfig",
    "MultiAssetMarketImpactEngine",
    "MutationConfig",
    "OASCovarianceEstimator",
    "OffspringResult",
    "OptimizationResult",
    "ParetoCohortStratifier",
    "ParetoFront",
    "ParetoSortingError",
    "PayoffTensorResult",
    "PositionSide",
    "ProbabilityCalibrator",
    "PurgedSplit",
    "RankingResult",
    "RegimeConfig",
    "RegimeEstimationResult",
    "RegimeState",
    "RepresentationChromosome",
    "ResidualOrthogonalityGate",
    "RiskChromosome",
    "SVDSubspaceOrthogonalArchive",
    "ScaleType",
    "StackelbergConfig",
    "StackelbergPayoffEngine",
    "StackelbergPayoffTensorConstructor",
    "StagnationDetector",
    "StagnationException",
    "StagnationReport",
    "StrategyChromosome",
    "StreamingFracDiffBuffer",
    "TripleBarrierConfig",
    "TwoStageMetaLabeler",
    "VectorizedNewtonSolver",
    "adjust_p_values_fdr",
    "compute_effective_trials",
    "compute_expected_max_sharpe",
    "compute_fractional_weights",
    "compute_min_backtest_length",
    "compute_moments",
    "compute_parkinson_volatility",
    "compute_probabilistic_sharpe_ratio",
]
